import { Theme } from './type';

export const THEME: Theme = {
  ACCENT_COLOR: '#41337A',
  BORDER_COLOR: '#D3D3D3',
  CARD_BACKGROUND: '#ededed',
  ERROR: '#FF4444',
  INFO: '#D3d3d3',
  MAIN_BACKGROUND: '#FFF',
  PRIMARY_COLOR: '#6EA4BF',
  SECONDARY_BACKGROUND: '#F8F9fA',
  SECONDARY_COLOR: '#C2EFEB',
  SUCCESS: '#4A934A,',
  TEXT_COLOR: '#4d5760',
  WARNING: '#FFBB33',
};
